### ISSUE TITLE
dev environment oauth forwards to production service

### ISSUE THREAD

**Issue by bengreenier** [hashtag-include/arewegood-web#3]
When running the dev server, and logging in with oauth, the callback directs to the production service, not the localhost version. this should be fixable with `redirect_uri` in the oauth call.

**Comment by bengreenier** [comment]
see [this](https://developer.github.com/v3/oauth/#redirect-urls)

**Comment by trjast** [comment]
can you get latest and double check this bug repros? im using two github applications each with separate callbacks (one dev and one prod) and everything is working properly for me. i already am specifying the redirect uri

**Comment by bengreenier** [comment]
verified; works fine. @mmichaud93 you should update your local repo, this looked like an issue on your box, but it's resolved in master
